### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by faroit** [k-chuang/automate-download-freesound#1]
Hi, I found this repo and I think this is of great use. I installed the requirements but got the following error when trying to run the script:

```
Login successful!
Traceback (most recent call last):
  File "automate_download_freesound.py", line 344, in <module>
    sys.exit(main(sys.argv))
  File "automate_download_freesound.py", line 335, in main
    download_count = simulate_download(elem, download_path, user_info.email, user_info.password, args)
  File "automate_download_freesound.py", line 209, in simulate_download
    driver.implicitly_wait(1)
  File "/Users/faro/repositories/automate-download-freesound/.env2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 790, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/Users/faro/repositories/automate-download-freesound/.env2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/faro/repositories/automate-download-freesound/.env2/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: value must be a non-negative integer
  (Session info: chrome=75.0.3770.142)
```

any idea where to fix this?

**Comment by faroit** [comment]
https://bugs.launchpad.net/ubuntu/+source/python-selenium/+bug/1833448

this does solve the problem. You might want to update the requirements.txt
